- name: "John Smith"
  title: "Senior Software Engineer"
  organization: "Tech Corp"
  email: "john.smith@techcorp.com"
  bio: "Experienced software engineer specializing in web development and cloud architecture. Passionate about open source and sustainable technology solutions."
  image: "/assets/images/john-smith.jpg"
  linkedin: "https://linkedin.com/in/johnsmith"
  github: "https://github.com/johnsmith"
  website: "https://johnsmith.dev"

- name: "Jane Doe"
  title: "Research Scientist"
  organization: "University Labs"
  email: "jane.doe@unilabs.edu"
  bio: "Climate science researcher focused on computational modeling and data analysis. Advocate for diversity in STEM fields."
  image: "/assets/images/jane-doe.jpg"
  linkedin: "https://linkedin.com/in/janedoe"
  github: "https://github.com/janedoe"
  website: "https://janedoe.org"

- name: "Mike Johnson"
  title: "Project Manager"
  organization: "Green Tech Solutions"
  email: "mike.johnson@greentech.com"
  bio: "Experienced project manager leading sustainable technology initiatives. Background in renewable energy systems and environmental policy."
  image: "/assets/images/mike-johnson.jpg"
  linkedin: "https://linkedin.com/in/mikejohnson"
  github: ""
  website: "https://greentech.com/team/mike"

- name: "Sarah Wilson"
  title: "Data Scientist"
  organization: "Analytics Inc"
  email: "sarah.wilson@analytics.com"
  bio: "Data scientist with expertise in machine learning and environmental data analysis. Contributor to open science initiatives."
  image: "/assets/images/sarah-wilson.jpg"
  linkedin: "https://linkedin.com/in/sarahwilson"
  github: "https://github.com/sarahwilson"
  website: ""